using BankTwo.Application.Data;
using System;
using System.Net;
using System.Net.Mail;

namespace BankTwo.Application.Logic.Utilities
{
    public class SendEmail
    {
        private const bool Success = true;
        private const bool Failure = false;
        private string CompanyMail = "gabiniche@gmail.com";
        private string CompanyMailPassword = "SuperAdministrator19";
       public bool SendUserEmail(string userMail,string password)
        {
            
            SmtpClient client = new SmtpClient("smtp.gmail.com");
            MailMessage mail = new MailMessage(CompanyMail,userMail);
            mail.Subject = "Bank Two User Password";
            mail.Body = "Bank Two Password is: \t" + password
                + "\n Change Password after LogIn";
            //587 - TLS required 465 - SSL Required
            client.Port = 465;
            client.Credentials = new NetworkCredential(CompanyMail,CompanyMailPassword);
            client.EnableSsl = true;
            try
            {
                client.Send(mail);
            }
            catch (Exception ex)
            {
                ErrorLogger.logError(ex.Message, ex.InnerException, ex.StackTrace);
                return Failure;
            };
            return Success;
        }
        public bool SendPasswordViaEmail(string email,string userName, string password)
        {
            try
            {
                SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587)
                {
                    EnableSsl = true,
                    Credentials = new NetworkCredential("gabiniche@gmail.com", "SuperAdministrator19")
                };
                SmtpClient server = smtpClient;
                MailMessage message = new MailMessage
                {
                    IsBodyHtml = true,
                    From = new MailAddress("raluchukwu.mbaebie@gmail.com", "Bank Two"),
                    Subject = " Bank Two Application Login Credentials"
                };
                message.To.Add(new MailAddress(email));
                message.IsBodyHtml = true;
                message.Body += "<b>Welcome to BANK TWO</b>";
                message.Body += "Your Username is: " + userName +"<br/>";
                message.Body += "Email: " + email + "<br/>";
                message.Body += "Your autogenerated password is: " + password + "<br/>";
                message.Body += "<br/>Change Autogenerated password after Login<br/>";
                message.Body += "<i>signed: BankTwo HR</i>";
           
                server.Send(message);

            }
            catch (Exception ex)
            {
                ErrorLogger.logError(ex.Message, ex.InnerException, ex.StackTrace);
                return Failure;
            }
            return Success;
        }

    }
}
